name: Deploy

on:
  push:
    branches:
      -main

jobs:
  build:
    run-on: ubuntu-latest
    steps: 
      -uses:actions/checkout@v2
      -uses:akhilehns/heroku-deploy@v3.12.12 #this is the action itself
       with:
        heroku_api_key:${[secrets.HEROKU_API_KEY]}
        heroku_app_name:"protected-chamber-20902"
        heroku_email: andrewtimkwan@gmail.com